name: Deploy via WireGuard

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install WireGuard
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard resolvconf

      - name: Setup WireGuard connection
        run: |
          echo "${{ secrets.WIREGUARD_CONFIG }}" | sudo tee /etc/wireguard/wg0.conf > /dev/null
          sudo chmod 600 /etc/wireguard/wg0.conf
          sudo wg-quick up wg0
          sleep 3

      - name: Verify WireGuard connection
        run: |
          sudo wg show
          echo "Testing connection to server..."
          ping -c 3 ${{ secrets.SERVER_VPN_IP }}
          ip addr show wg0

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_VPN_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            git pull origin main
            ./docker-deploy-bot.sh

      - name: Cleanup WireGuard
        if: always()
        run: |
          sudo wg-quick down wg0 || true
