name: Trigger Central Deploy

on:
  push:
    branches:
      - "dev"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send dispatch to central
        env:
          PAT: ${{ secrets.DISPATCH_PAT }}
          CENTRAL_REPO: Hadamot/tech-conditions
          WORKING_PATH: /var/opt/Docker/dev_hr_bot
          ENV_FILE_URL: ${{ secrets.DEV_ENV_FILE_URL }}
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $PAT" \
          https://api.github.com/repos/$CENTRAL_REPO/dispatches \
          -d '{
            "event_type": "trigger-deploy",
            "client_payload": {
              "repository": "${{ github.repository }}",
              "ref": "${{ github.ref }}",
              "working_path": "'"$WORKING_PATH"'",
              "env_url": "'"$ENV_FILE_URL"'"
            }
          }'
